
package VaccinationProgram;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;


public class FrmAddVaccinePersonnel extends javax.swing.JFrame {
    String vacID, vacName, vacCOO, vacDoses, frmAccID, name;
    Boolean verifyExistence;

    
    FrmAddVaccinePersonnel(String aID, String n){
        this.frmAccID = aID;
        this.name = n;
        initComponents();
    }
    public FrmAddVaccinePersonnel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vaccineIdTxtBox = new javax.swing.JTextField();
        nameTxtBox = new javax.swing.JTextField();
        COOtxtBox = new javax.swing.JTextField();
        dosesTxtBox = new javax.swing.JTextField();
        addNewBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("New Vaccine Information");

        jLabel4.setText("Vaccine ID:");

        jLabel6.setText("Name:");

        jLabel7.setText("Country Of Origin:");

        jLabel8.setText("Doses:");

        COOtxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                COOtxtBoxKeyTyped(evt);
            }
        });

        dosesTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dosesTxtBoxKeyTyped(evt);
            }
        });

        addNewBtn.setText("Add New");
        addNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(vaccineIdTxtBox)
                                .addComponent(COOtxtBox)
                                .addComponent(dosesTxtBox)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(addNewBtn)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vaccineIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(COOtxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dosesTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(addNewBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
        vacID = vaccineIdTxtBox.getText();
        vacName = nameTxtBox.getText();
        vacCOO = COOtxtBox.getText();
        vacDoses = dosesTxtBox.getText();
        
        //Check whether vaccine ID is unique or not
        try
        {
            File file = new File("Vaccine.txt");
            BufferedReader br = new BufferedReader(new FileReader(file));
            String checkLine = null;
            verifyExistence = false;
            while((checkLine = br.readLine()) != null)
            {
                String [] temp = checkLine.split(";");
                if(temp[0].equals(vacID))
                    {
                        verifyExistence = true;
                        break;
                    }
            }
            br.close();
        }
        catch(IOException ioe)
        {
           JOptionPane.showMessageDialog(null, "There is an error in the system!\nPlease try again later.", "Error",JOptionPane.WARNING_MESSAGE);
        }
        
        //Vaccine ID is not unique
        if(verifyExistence == true)
        {
            JOptionPane.showMessageDialog(null, "Vaccine Already Registered!", "Error",JOptionPane.WARNING_MESSAGE);
            vaccineIdTxtBox.setText("");
            vaccineIdTxtBox.requestFocusInWindow();
        }
        //Empty Fields
        else if(vacID.equals("") || vacName.equals("") ||vacCOO.equals("") || vacDoses.equals(""))
        {
          JOptionPane.showMessageDialog(null, "Please fill in all fields!", "Error",JOptionPane.WARNING_MESSAGE);
        }
        //All info is validated, call add vaccine method
        else
        {
            Personnel psn = new Personnel();
            boolean add = psn.addVaccine(vacID, vacName, vacCOO, vacDoses);
            if(add == true){
                JOptionPane.showMessageDialog(null, "Vaccine information is modified successfully.", "Vaccine Modified",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new FrmVaccineInformationPersonnel(frmAccID,name).setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "There is an error in the system!"
                        + "\nPlease try again later.", "Error",JOptionPane.WARNING_MESSAGE);
                this.dispose();
                new FrmVaccineInformationPersonnel(frmAccID,name).setVisible(true);
            }
        }
        
        
    }//GEN-LAST:event_addNewBtnActionPerformed

    private void dosesTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dosesTxtBoxKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_dosesTxtBoxKeyTyped

    private void COOtxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_COOtxtBoxKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isAlphabetic(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_COOtxtBoxKeyTyped

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new FrmPersonnelMainMenu(frmAccID,name).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new FrmPersonnelMainMenu(frmAccID,name).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddVaccinePersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddVaccinePersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddVaccinePersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddVaccinePersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAddVaccinePersonnel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField COOtxtBox;
    private javax.swing.JButton addNewBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dosesTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameTxtBox;
    private javax.swing.JTextField vaccineIdTxtBox;
    // End of variables declaration//GEN-END:variables
}
